export default function Head() {
    return (
      <>
        <title>Jose&apos;s Personal Website</title>
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/smile.svg" />
      </>
    )
  }